#!/usr/bin/env julia
# Generates Julia-reference parity data for the dcolpp::socp forward solve,
# by running the ORIGINAL DifferentiableCollisions.jl on random poses and
# emitting a C++ header the Catch2 test suite includes directly (no runtime
# file I/O / working-directory issues).
#
# Frame convention: DCJ's `proximity(prim1, prim2)` uses each primitive's own
# world-frame (r, q). DCOL++ instead takes the two primitives as an implicit
# body-1-frame pair plus a single relative transform g = g1^{-1} g2. This
# script computes that g from DCJ's (r1,q1)/(r2,q2) and re-expresses the
# witness point in body 1's frame, so the two libraries' outputs are
# directly comparable.
#
# Usage: julia --project=<path to DifferentiableCollisions.jl> tools/gen_socp_reference.jl > tests/generated/socp_reference_data.hpp

using DifferentiableCollisions
using StaticArrays, LinearAlgebra, Random
const DCD = DifferentiableCollisions

Random.seed!(20260820)

function dcm_from_q(q)
    q4, q1, q2, q3 = normalize(q)
    @SMatrix [
        (2*q1^2+2*q4^2-1)  2*(q1*q2-q3*q4)    2*(q1*q3+q2*q4);
        2*(q1*q2+q3*q4)    (2*q2^2+2*q4^2-1)  2*(q2*q3-q1*q4);
        2*(q1*q3-q2*q4)    2*(q2*q3+q1*q4)    (2*q3^2+2*q4^2-1)
    ]
end

# emits one test case: relative g (row-major 4x4), expected alpha, expected
# witness point in body-1 frame.
function emit_case(io, prim1, prim2, ntrials::Int)
    for _ in 1:ntrials
        r1 = 2 .* (@SVector randn(3))
        q1 = normalize(@SVector randn(4))
        r2 = 2 .* (@SVector randn(3))
        q2 = normalize(@SVector randn(4))

        prim1.r = r1; prim1.q = q1
        prim2.r = r2; prim2.q = q2

        alpha, x = DCD.proximity(prim1, prim2; pdip_tol=1e-10)

        R1 = dcm_from_q(q1)
        R2 = dcm_from_q(q2)
        g = zeros(4, 4)
        g[1:3, 1:3] = R1' * R2
        g[1:3, 4] = R1' * (r2 - r1)
        g[4, 4] = 1.0

        x_local = R1' * (x - r1)

        gvals = join(vec(permutedims(g)), ", ")  # row-major flatten
        println(io, "    { {", gvals, "}, ", alpha, ", {", x_local[1], ", ", x_local[2], ", ", x_local[3], "} },")
    end
end

io = stdout
println(io, "// Auto-generated by tools/gen_socp_reference.jl -- DO NOT EDIT BY HAND.")
println(io, "// Reference (alpha, witness point) pairs from the original")
println(io, "// DifferentiableCollisions.jl (Kevin Tracy, MIT), for numeric-parity")
println(io, "// testing of dcolpp::socp's forward solve. See NOTICE.md.")
println(io, "#pragma once")
println(io, "#include \"socp_ref_case.hpp\"")
println(io, "namespace dcolpp::test_ref {")

pairs = [
    ("SphereSphere", () -> (DCD.Sphere(0.5), DCD.Sphere(0.3))),
    ("SphereCapsule", () -> (DCD.Sphere(0.4), DCD.Capsule(0.3, 1.2))),
    ("CapsuleCylinder", () -> (DCD.Capsule(0.3, 1.2), DCD.Cylinder(0.25, 0.9))),
    ("CylinderCone", () -> (DCD.Cylinder(0.25, 0.9), DCD.Cone(1.2, deg2rad(22)))),
    ("ConePolytope", () -> (DCD.Cone(1.2, deg2rad(22)), make_cube())),
    ("PolytopeEllipsoid", () -> (make_cube(), DCD.Ellipsoid(SMatrix{3,3}(Diagonal([1/0.6^2, 1/0.4^2, 1/0.5^2])))),),
    ("EllipsoidPolygon", () -> (DCD.Ellipsoid(SMatrix{3,3}(Diagonal([1/0.6^2, 1/0.4^2, 1/0.5^2]))), make_hex())),
    ("PolygonSphere", () -> (make_hex(), DCD.Sphere(0.35))),
]

function make_cube()
    A = SMatrix{6,3}([1.0 0 0; -1 0 0; 0 1 0; 0 -1 0; 0 0 1; 0 0 -1])
    b = SVector{6}(fill(0.5, 6))
    DCD.Polytope(A, b)
end

function make_hex()
    N = 6
    ns = [ [cos(th); sin(th)] for th in 0:(2*pi/N):(2*pi*(N-1)/N) ]
    A = SMatrix{N,2}(vcat(transpose.(ns)...))
    b = SVector{N}(fill(0.4, N))
    DCD.Polygon(A, b, 0.1)
end

for (name, ctor) in pairs
    p1, p2 = ctor()
    println(io, "inline const SocpRefCase ", name, "[] = {")
    emit_case(io, p1, p2, 8)
    println(io, "};")
    println(io, "inline constexpr int ", name, "Count = 8;")
end

println(io, "} // namespace dcolpp::test_ref")
